name: CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Clear npm cache
      run: npm cache clean --force
      working-directory: .

    - name: Install dependencies
      run: npm install
      working-directory: .

    - name: Fix Jest permissions
      run: chmod +x node_modules/.bin/jest
      working-directory: .
      
    - name: Run tests
      run: npm test
      working-directory: .
